[project]
name = "pdf-rag-application"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "groq>=1.6.0",
    "inngest>=0.5.19",
    "llama-index-core>=0.14.24",
    "llama-index-readers-file>=0.6.0",
    "openai>=3.3.1",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.0",
    "streamlit>=1.62.0",
    "uvicorn>=0.52.4",
    "voyageai>=0.5.0",
]
